version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - chatbot-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - chatbot-network
    environment:
      - BACKEND_URL=http://backend:8000/bedrock-chat

# Define the network
networks:
  chatbot-network:
    driver: bridge
