name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    name: Lint & Checks
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install ruff black isort

      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .

      - name: Run Isort
        run: isort --check-only .

  build-and-deploy:
    name: Build & Deploy Docker
    runs-on: self-hosted
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - name: Build and run Docker Compose
        run: |
          cd ~/chatbot_azercell
          docker-compose down
          docker-compose up -d --build
